[package]
name = "recite-util"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = { version = "1.3.0" }
inquire = "0.7.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
